// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package bootstrap

import (
	"github.com/casbin/casbin/v2"
	"github.com/gin-gonic/gin"
	"github.com/spf13/viper"
	"go-base-system-v2/internal/authz"
	"go-base-system-v2/internal/conf"
	"go-base-system-v2/internal/db"
	"go-base-system-v2/internal/handler"
	"go-base-system-v2/internal/repository"
	"go-base-system-v2/internal/server"
	"go-base-system-v2/internal/service"
	"go-base-system-v2/pkg/logger"
	"go.uber.org/zap"
	"gorm.io/gorm"
)

// Injectors from wire.go:

// InitializeApp 是我们主要的 Wire injector。
// 它接收 ConfigOptions (包含配置文件路径)，初始化所有核心组件，并返回 App 实例和总的清理函数。
func InitializeApp(cfgOpts conf.ConfigOptions) (*App, func(), error) {
	viper, err := conf.ProvideViper(cfgOpts)
	if err != nil {
		return nil, nil, err
	}
	sugaredLogger, cleanup, err := logger.ProvideZapLogger(viper)
	if err != nil {
		return nil, nil, err
	}
	gormDB, cleanup2, err := db.ProvideGormDB(viper, sugaredLogger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	userRepository := repository.NewUserRepository(gormDB, sugaredLogger)
	enforcer, err := authz.ProvideCasbinEnforcer(viper, gormDB, sugaredLogger)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	userService := service.NewUserService(userRepository, enforcer, sugaredLogger, viper)
	healthHandler := handler.NewHealthHandler(sugaredLogger)
	userHandler := handler.NewUserHandler(userService, sugaredLogger)
	engine, err := server.NewGinEngine(viper, sugaredLogger, healthHandler, userHandler, enforcer)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	app := NewApp(viper, sugaredLogger, gormDB, userRepository, userService, engine, enforcer)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

// App 结构体聚合了应用的核心组件实例。
// 这些实例将由 Wire 自动构建和注入。
type App struct {
	Config   *viper.Viper              // Viper 配置实例
	Logger   *zap.SugaredLogger        // Zap SugaredLogger 实例
	DB       *gorm.DB                  // GORM 数据库连接实例
	UserRepo repository.UserRepository // 用户数据仓库接口实例
	UserSvc  service.UserService       // 用户服务接口实例
	Engine   *gin.Engine               // Gin HTTP 引擎实例
	Enforcer *casbin.Enforcer          // Casbin Enforcer 实例

}

// NewApp 是 App 结构体的构造函数 Provider。
// Wire 会调用此函数来创建 App 实例，并自动注入其依赖项。
func NewApp(
	cfg *viper.Viper,
	zapLogger *zap.SugaredLogger,
	gormDB *gorm.DB,
	userRepo repository.UserRepository,
	userSvc service.UserService,
	engine *gin.Engine,
	enforcer *casbin.Enforcer,
) *App {
	return &App{
		Config:   cfg,
		Logger:   zapLogger,
		DB:       gormDB,
		UserRepo: userRepo,
		UserSvc:  userSvc,
		Engine:   engine,
		Enforcer: enforcer,
	}
}
