// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "https://www.example.com/support",
            "email": "support@example.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "description": "检查 API 服务是否正常运行并可达。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "健康检查 (Health Check)"
                ],
                "summary": "服务健康检查 (Service Health Check)",
                "responses": {
                    "200": {
                        "description": "成功\" // 更新 Success 注解",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.ResponseData"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object",
                                            "additionalProperties": {
                                                "type": "string"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/users/id/{id}": {
            "get": {
                "description": "通过指定的用户ID检索用户的详细信息。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户 (User)"
                ],
                "summary": "根据用户ID获取用户信息 (Get User By ID)",
                "parameters": [
                    {
                        "type": "integer",
                        "format": "uint",
                        "description": "用户ID (User ID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功获取用户信息",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.ResponseData"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.User"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "无效的用户ID",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    },
                    "404": {
                        "description": "用户未找到",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    }
                }
            }
        },
        "/users/register": {
            "post": {
                "description": "根据提供的用户名、邮箱和密码创建一个新用户。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户 (User)"
                ],
                "summary": "用户注册 (Register User)",
                "parameters": [
                    {
                        "description": "用户注册请求体",
                        "name": "user_register_req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UserRegisterReq"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "用户创建成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.ResponseData"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.User"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误\" // data 通常为 nil 或包含具体错误信息的对象",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    }
                }
            }
        },
        "/users/username/{username}": {
            "get": {
                "description": "通过指定的用户名检索用户的详细信息。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户 (User)"
                ],
                "summary": "根据用户名获取用户信息 (Get User By Username)",
                "parameters": [
                    {
                        "maxLength": 50,
                        "minLength": 3,
                        "type": "string",
                        "description": "用户名 (Username)",
                        "name": "username",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功获取用户信息",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.ResponseData"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.User"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    },
                    "404": {
                        "description": "用户未找到",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseData"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.UserRegisterReq": {
            "type": "object",
            "required": [
                "email",
                "password",
                "username"
            ],
            "properties": {
                "email": {
                    "description": "Email 是用户的电子邮件地址。\n` + "`" + `json:\"email\"` + "`" + `: 在 JSON 中此字段名为 \"email\"。\n` + "`" + `binding:\"required,email\"` + "`" + `: 此字段为必填项，并且必须符合电子邮件的格式。",
                    "type": "string"
                },
                "password": {
                    "description": "Password 是用户设置的密码。\n` + "`" + `json:\"password\"` + "`" + `: 在 JSON 中此字段名为 \"password\"。\n` + "`" + `binding:\"required,min=8,max=100\"` + "`" + `: 此字段为必填项，长度必须在 8 到 100 个字符之间。",
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 8
                },
                "username": {
                    "description": "Username 是用户期望的登录名。\n` + "`" + `json:\"username\"` + "`" + `: 在 JSON 中此字段名为 \"username\"。\n` + "`" + `binding:\"required,min=3,max=50\"` + "`" + `: 此字段为必填项，长度必须在 3 到 50 个字符之间。",
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 3
                }
            }
        },
        "model.User": {
            "type": "object",
            "properties": {
                "created_at": {
                    "description": "CreatedAt 记录用户创建的时间。\nGORM 会在创建记录时自动填充此字段。",
                    "type": "string"
                },
                "email": {
                    "description": "Email 是用户的电子邮件地址。\n设置了唯一索引 (uniqueIndex) 以确保电子邮件的唯一性。\n允许为空 (default:null)，因为用户可能在注册初期不提供邮箱。",
                    "type": "string"
                },
                "id": {
                    "description": "ID 是用户的主键，类型为 uint，并且在数据库中自增。",
                    "type": "integer"
                },
                "updated_at": {
                    "description": "UpdatedAt 记录用户最后更新的时间。\nGORM 会在创建和更新记录时自动填充此字段。",
                    "type": "string"
                },
                "username": {
                    "description": "Username 是用户的唯一标识名。\n设置了唯一索引 (uniqueIndex) 以确保用户名的唯一性。\n不能为空 (not null)。",
                    "type": "string"
                }
            }
        },
        "response.ResponseData": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "业务状态码",
                    "type": "integer"
                },
                "data": {
                    "description": "响应数据"
                },
                "msg": {
                    "description": "响应消息",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1 // **确保与 NewGinEngine 中注册的路由组路径一致**",
	Schemes:          []string{"http", "https"},
	Title:            "Go Base System API V2",
	Description:      "这是一个使用 Golang (Gin, GORM, Wire) 构建的基础系统 API 服务第二版。",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
